### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Peaceful-555**

### CODE REVIEW

**Review by Chinmay-jain767 — CHANGES_REQUESTED** [review]
Run the jupyter notebook and show the outputs cells.

**Comment by Peaceful-555** [comment]
I am getting this error "RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:76] data. DefaultCPUAllocator: not enough memory: you tried to allocate 25165824 bytes" while running the last loop and its not getting resolved.

**Comment by I-am-sayantan** [comment]
Have you ran the code ? Is it during the computation or when you putting it inside the git?

**Comment by Peaceful-555** [comment]
Yes I ran the code. Its during computation.

**Comment by I-am-sayantan** [comment]
> Yes I ran the code. Its during computation.

Use lesser number of rows, take one month of data

**Pull request closed without merging**
