### PR TITLE
Enhanced the Readme file

### PR DESCRIPTION
**Pull request by Chayan-11**
@I-am-sayantan  Made the following Changes:
* Shifted the alignment of the text `Public-sentiment-analysis-based-on-twitter-hashtags` to the center
* Added the `Contributor's List` at the end
Please review the changes and merge the PR if that fits your project's Readme.

### CODE REVIEW

**Review by I-am-sayantan — CHANGES_REQUESTED** [review]
**_Please make PR in the contribution branch_**

**Comment by Chayan-11** [comment]
Made my PR in Contributors branch @I-am-sayantan

**Comment by I-am-sayantan** [comment]
> Made my PR in Contributors branch @I-am-sayantan 

But here the pr is in main, please recheck

**Comment by Chayan-11** [comment]
Sorry for the inconviniences. I think now it would work fine

**Comment by I-am-sayantan** [comment]
_**You have done great , but I think you are not understanding what I am trying to say:

See this repo have two branches : Main and CONTRIBUTION

If you make any PR you have to make it in the CONTRIBUTION, not check-in the top you are making it in the main branch, hence we can't accept it, so you have to change the branch to contribution then make the PR.

For readme no need to go inside the contribution folder make changes in the readme directly, I have reviewed it, it is really good, we will marge that once you make the PR in the contribution branch.**_

**Pull request closed without merging**
